// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP005 - RE-SQUAWK OR QUOTE SQUAWK', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP005 - RE-SQUAWK OR QUOTE SQUAWK', async function() {
    // Test name: CP005 - RE-SQUAWK OR QUOTE SQUAWK
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1280x720 | 
    await driver.manage().window().setRect({ width: 1280, height: 720 })
    // 3 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 4 | type | name=email | holaaaa@gmail.com
    // EMAIL
    await driver.findElement(By.name("email")).sendKeys("holaaaa@gmail.com")
    // 5 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 6 | type | name=password | holaaaa
    // PASSWORD
    await driver.findElement(By.name("password")).sendKeys("holaaaa")
    // 7 | click | name=login | 
    await driver.findElement(By.name("login")).click()
    // 8 | click | name=status | 
    // MESSAGE
    await driver.findElement(By.name("status")).click()
    // 9 | type | name=status | holaaaa
    await driver.findElement(By.name("status")).sendKeys("holaaaa")
    // 10 | click | id=tweet-input | 
    // SQUAWK BUTTON
    await driver.findElement(By.id("tweet-input")).click()
    // 11 | click | css=.box-tweet:nth-child(3) .grid-box-reaction:nth-child(2) > .hover-reaction > .fas | 
    // RETWEETEAR
    await driver.wait(until.elementLocated(By.css('.hover-reaction.hover-reaction-retweet.retweet.option')), 5000);
    await driver.findElement(By.css('.hover-reaction.hover-reaction-retweet.retweet.option')).click();
    // 12 | click | css=li > .fa-retweet | 
    await driver.wait(until.elementLocated(By.css('.retweet-i')), 5000);
    await driver.findElement(By.css('.retweet-i')).click();    
  })
})
