// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP009 - ACTUALIZAR CREDENCIALES', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP009 - ACTUALIZAR CREDENCIALES', async function() {
    // Test name: CP009 - ACTUALIZAR CREDENCIALES
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1280x720 | 
    await driver.manage().window().setRect({ width: 1280, height: 720 })
    // 3 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 4 | type | name=email | holaaaa@gmail.com
    // EMAIL
    await driver.findElement(By.name("email")).sendKeys("holaaaa@gmail.com")
    // 5 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 6 | type | name=password | holaaaa
    // PASSWORD
    await driver.findElement(By.name("password")).sendKeys("holaaaa")
    // 7 | click | name=login | 
    await driver.findElement(By.name("login")).click()
    // 8 | click | css=.grid-sidebar:nth-child(9) img | 
    await driver.findElement(By.css(".grid-sidebar:nth-child(9) img")).click()
    // 9 | click | id=v-pills-profile-tab | 
    // OPTION CHANGE PASSWORD
    await driver.findElement(By.id("v-pills-profile-tab")).click()
    // 10 | click | name=old_password | 
    await driver.findElement(By.name("old_password")).click()
    // 11 | type | name=old_password | javier2023
    // OLD PASSWORD
    await driver.findElement(By.name("old_password")).sendKeys("javier2023")
    // 12 | click | name=new_password | 
    await driver.findElement(By.name("new_password")).click()
    // 13 | type | name=new_password | javier2023-2.0
    // NEW PASSWORD
    await driver.findElement(By.name("new_password")).sendKeys("javier2023-2.0")
    // 14 | click | name=ver_password | 
    await driver.findElement(By.name("ver_password")).click()
    // 15 | type | name=ver_password | javieer2023-2.0
    // REPEAT - NEW PASSWORD
    await driver.findElement(By.name("ver_password")).sendKeys("javieer2023-2.0")
    // 16 | click | css=.text-center:nth-child(5) > .btn | 
    // SAVE CHANGES - PASSWORD
    await driver.findElement(By.css(".text-center:nth-child(5) > .btn")).click()
    // 17 | click | id=v-pills-home-tab | 
    // OPTION EMAIL OR USERNAME
    await driver.findElement(By.id("v-pills-home-tab")).click()
    // 18 | click | id=exampleInputEmail1 | 
    await driver.findElement(By.id("exampleInputEmail1")).click()
    // 19 | type | id=exampleInputEmail1 | javier2.0@gmail.com
    // ACTUALIZAR EMAIL
    await driver.findElement(By.id("exampleInputEmail1")).sendKeys("javier2.0@gmail.com")
    // 20 | click | id=exampleInputPassword1 | 
    await driver.findElement(By.id("exampleInputPassword1")).click()
    // 21 | type | id=exampleInputPassword1 | javiM02-2.0
    // ACTUALIZAR USERNAME
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("javiM02-2.0")
    // 22 | click | name=submit | Save Changes
    // GUARDAR LOS DATOS DE EMAIL OR USERNAME
    await driver.findElement(By.name("submit")).click()
  })
})
