// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP006 - VISUALIZAR PROFILE', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP006 - VISUALIZAR PROFILE', async function() {
    // Test name: CP006 - VISUALIZAR PROFILE
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1280x720 | 
    await driver.manage().window().setRect({ width: 1280, height: 720 })
    // 3 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 4 | type | name=email | holaaaa@gmail.com
    // EMAIL
    await driver.findElement(By.name("email")).sendKeys("holaaaa@gmail.com")
    // 5 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 6 | type | name=password | holaaaa
    // PASSWORD
    await driver.findElement(By.name("password")).sendKeys("holaaaa")
    // 7 | click | name=login | 
    await driver.findElement(By.name("login")).click()
    // 8 | click | css=.grid-sidebar:nth-child(7) img | 
    await driver.findElement(By.css(".grid-sidebar:nth-child(7) img")).click()
    // 9 | click | id=home-tab | 
    // HOME
    await driver.findElement(By.id("home-tab")).click()
    // 10 | click | id=profile-tab | 
    // PROFILE
    await driver.findElement(By.id("profile-tab")).click()
    // 12 | click | css=.count-following-i | 
  })
})
