// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP007 - ACTUALIZAR INFORMACION', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP007 - ACTUALIZAR INFORMACION', async function() {
    // Test name: CP007 - ACTUALIZAR INFORMACION
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1280x720 | 
    await driver.manage().window().setRect({ width: 1280, height: 720 })
    // 3 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 4 | type | name=email | holaaaa@gmail.com
    // EMAIL
    await driver.findElement(By.name("email")).sendKeys("holaaaa@gmail.com")
    // 5 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 6 | type | name=password | holaaaa
    // PASSWORD
    await driver.findElement(By.name("password")).sendKeys("holaaaa")
    // 7 | click | name=login | 
    await driver.findElement(By.name("login")).click()
    // 8 | click | css=.grid-sidebar:nth-child(7) img | 
    await driver.findElement(By.css(".grid-sidebar:nth-child(7) img")).click()
    // 9 | click | css=.home-edit-button | 
    await driver.findElement(By.css(".home-edit-button")).click()
    // 10 | click | name=bio | 
    await driver.findElement(By.name("bio")).click()
    // 11 | type | name=bio | Hi, welcome to my blog
    // BIO
    await driver.findElement(By.name("bio")).sendKeys("Hi, welcome to my blog")
    // 12 | click | name=website | 
    await driver.findElement(By.name("website")).click()
    // 13 | type | name=website | none
    // WEB-SITE
    await driver.findElement(By.name("website")).sendKeys("none")
    // 14 | click | id=exampleInputPassword1 | 
    await driver.findElement(By.id("exampleInputPassword1")).click()
    // 15 | type | id=exampleInputPassword1 | Bogotá D.C., Colombia
    // ADDRESS
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("Bogotá D.C., Colombia")
    // 16 | click | name=update | 
    // UPDATE
    await driver.findElement(By.name("update")).click()
  })
})
