// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP008 - CONFIGURACIONES', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP008 - CONFIGURACIONES', async function() {
    // Test name: CP008 - CONFIGURACIONES
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1280x720 | 
    await driver.manage().window().setRect({ width: 1280, height: 720 })
    // 3 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 4 | type | name=email | holaaaa@gmail.com
    // EMAIL
    await driver.findElement(By.name("email")).sendKeys("holaaaa@gmail.com")
    // 5 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 6 | type | name=password | holaaaa
    // PASSWORD
    await driver.findElement(By.name("password")).sendKeys("holaaaa")
    // 7 | click | name=login | 
    await driver.findElement(By.name("login")).click()
    // 8 | click | css=.grid-sidebar:nth-child(9) img | 
    await driver.findElement(By.css(".grid-sidebar:nth-child(9) img")).click()
    // 9 | click | id=v-pills-profile-tab | 
    // OPTION CHANGE PASSWORD
    await driver.findElement(By.id("v-pills-profile-tab")).click()
    // 10 | click | name=old_password | 
    // OLD PASSWORD
    await driver.findElement(By.name("old_password")).click()
    // 11 | click | name=new_password | 
    // NEW PASSWORD
    await driver.findElement(By.name("new_password")).click()
    // 12 | click | name=ver_password | 
    // REPEAT - NEW PASSWORD
    await driver.findElement(By.name("ver_password")).click()
    // 13 | click | id=v-pills-home-tab | 
    // OPTION EMAIL OR USERNAME
    await driver.findElement(By.id("v-pills-home-tab")).click()
    // 14 | click | id=exampleInputEmail1 | 
    // ACTUALIZAR EMAIL
    await driver.findElement(By.id("exampleInputEmail1")).click()
    // 15 | click | id=exampleInputPassword1 | 
    // ACTUALIZAR USERNAME
    await driver.findElement(By.id("exampleInputPassword1")).click()
  })
})
