// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP011 - VISUALIZAR', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP011 - VISUALIZAR', async function() {
    // Test name: CP011 - VISUALIZAR
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1280x720 | 
    await driver.manage().window().setRect({ width: 1280, height: 720 })
    // 3 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 4 | type | name=email | holaaaa@gmail.com
    // EMAIL
    await driver.findElement(By.name("email")).sendKeys("holaaaa@gmail.com")
    // 5 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 6 | type | name=password | holaaaa
    // PASSWORD
    await driver.findElement(By.name("password")).sendKeys("holaaaa")
    // 7 | click | name=login | 
    await driver.findElement(By.name("login")).click()
    // 8 | click | css=.wrapper-left-active > strong | 
    // HOME TAB
    await driver.findElement(By.css(".wrapper-left-active > strong")).click()
    // 9 | click | css=.form-control | 
    // SEARCH
    await driver.findElement(By.css(".form-control")).click()
    // 10 | type | css=.form-control | juan
    await driver.findElement(By.css(".form-control")).sendKeys("juan")
    // 11 | click | css=.grid-sidebar:nth-child(5) strong | 
    // NOTIFICATION TAB
    await driver.findElement(By.css(".grid-sidebar:nth-child(5) strong")).click()
    // 12 | click | css=.form-control | 
    // SEARCH
    await driver.findElement(By.css(".form-control")).click()
    // 13 | type | css=.form-control | juan
    await driver.findElement(By.css(".form-control")).sendKeys("juan")
    // 14 | click | css=.grid-sidebar:nth-child(7) strong | 
    // PROFILE TAB
    await driver.findElement(By.css(".grid-sidebar:nth-child(7) strong")).click()
    // 15 | click | css=.search-input | 
    // SEARCH
    await driver.findElement(By.css(".search-input")).click()
    // 16 | type | css=.search-input | juan
    await driver.findElement(By.css(".search-input")).sendKeys("juan")
    // 17 | click | css=.grid-sidebar:nth-child(9) strong | 
    // SETTINGS TAB
    await driver.findElement(By.css(".grid-sidebar:nth-child(9) strong")).click()
    // 18 | click | css=.search-input | 
    // SEARCH
    await driver.findElement(By.css(".search-input")).click()
    // 19 | type | css=.search-input | juan
    await driver.findElement(By.css(".search-input")).sendKeys("juan")
  })
})
