// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP010 - INTERACCIONES', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP010 - INTERACCIONES', async function() {
    // Test name: CP010 - INTERACCIONES
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1280x720 | 
    await driver.manage().window().setRect({ width: 1280, height: 720 })
    // 3 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 4 | type | name=email | holaaaa@gmail.com
    // EMAIL
    await driver.findElement(By.name("email")).sendKeys("holaaaa@gmail.com")
    // 5 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 6 | type | name=password | holaaaa
    // PASSWORD
    await driver.findElement(By.name("password")).sendKeys("holaaaa")
    // 7 | click | name=login | 
    await driver.findElement(By.name("login")).click()
    // 8 | click | css=.position-relative > img | 
    // NOTIFICATION TAB
    await driver.findElement(By.css(".position-relative > img")).click()
    // 9 | click | css=.home-name | Notifications
    // LISTA DE NOTIFICACIONES
    await driver.findElement(By.css(".home-name")).click()
  })
})
